### ISSUE TITLE
Traders & Tasks Selection Incorrect

### ISSUE THREAD

**Issue by biffdit** [DoctorSoup143/The-Tarkov-Handbook#6]
Therapist & Peacekeeper have the same quests/tasks. 

![2020-01-08_12-59-16](https://user-images.githubusercontent.com/59664385/72007188-bf65a380-3216-11ea-8b6c-3d7df2b09f19.gif)

**Comment by DoctorSoup143** [comment]
This is currently my main priority to fix. I haven't fully added the Peacekeeper quests so its currently set to show Therapist. This will be fixed soon.

**Comment by biffdit** [comment]
Awesome. Glad to hear you're working on it. This issue was really the only one I had when running through it. Otherwise this is probably by far my favorite 'wiki' of sorts for Tarkov. It's helped me tremendously. Fabulous job.

**Comment by DoctorSoup143** [comment]
Updated and fixed in v0.2.4
