### ISSUE TITLE
QoL fixes / changes

### ISSUE THREAD

**Issue by biffdit** [DoctorSoup143/The-Tarkov-Handbook#7]
Ability to adjust the interface sound without having to do so through windows volume mixer. Maybe a slider or a volume bar kind of like what vimeo uses on their videos.

Ability to click a border-less full-screen button that you can select instead of pressing alt+enter. Another option could be that if you select full screen it automatically goes to full-screen border-less and if you hover at the top it brings down the bar to change it back. 

**Maps**

When in maps, I saw that you already plan to add exfils. Could it be possible to add filters to add/remove markers once more things are added? 

I'm not sure if you want these sorts of things here in issues or not. Let me know if I should send these elsewhere.

I'm really liking the app so far. Great stuff.

**Comment by DoctorSoup143** [comment]
@biffdit This is the best place to submit issues as i can track them easily. Feel free to continue doing what you're doing. Hopefully if this grown in popularity ill be able to add even more.

**Comment by DoctorSoup143** [comment]
Handbook moved.
https://www.reddit.com/r/EscapefromTarkov/comments/f4hlnx/the_tarkov_handbook/
